# Generated by Django 2.0 on 2018-02-17 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_auto_20180217_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='endTime',
            field=models.IntegerField(choices=[(0, '오전'), (1, '오후')], max_length=1),
        ),
        migrations.AlterField(
            model_name='leave',
            name='startTime',
            field=models.IntegerField(choices=[(0, '오전'), (1, '오후')], max_length=1),
        ),
    ]
