# Generated by Django 2.0 on 2018-02-17 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0004_auto_20180217_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='givenLeave',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='employee',
            name='usedLeave',
            field=models.IntegerField(default=0),
        ),
    ]
