# Generated by Django 2.0 on 2018-02-17 06:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0005_auto_20180217_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='givenLeave',
            field=models.DecimalField(decimal_places=2, default=15, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='usedLeave',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='leave',
            name='endTime',
            field=models.PositiveSmallIntegerField(choices=[(0, '오전'), (1, '오후')]),
        ),
        migrations.AlterField(
            model_name='leave',
            name='startTime',
            field=models.PositiveSmallIntegerField(choices=[(0, '오전'), (1, '오후')]),
        ),
    ]
