# Generated by Django 2.0 on 2018-02-17 06:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0006_auto_20180217_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='givenLeave',
            field=models.DecimalField(decimal_places=1, default=15, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='usedLeave',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(50)]),
        ),
    ]
