# Generated by Django 2.0 on 2018-02-22 11:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0007_auto_20180217_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='leftLeave',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
