# Generated by Django 2.0 on 2018-02-22 16:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0008_employee_leftleave'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='leaveLen',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
