# Generated by Django 2.0 on 2018-02-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0009_leave_leavelen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='endTime',
            field=models.CharField(choices=[('오전', '오전'), ('오후', '오후')], max_length=3),
        ),
        migrations.AlterField(
            model_name='leave',
            name='startTime',
            field=models.CharField(choices=[('오전', '오전'), ('오후', '오후')], max_length=3),
        ),
    ]
