# Generated by Django 2.0 on 2018-02-22 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0010_auto_20180222_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='late',
            field=models.IntegerField(default=0),
        ),
    ]
